name: month_year_picker
description: The month year picker inspired by the Flutter's date picker design.
version: 0.3.0+1
homepage: https://github.com/zulfahmi93/month-year-picker
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
